<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Thay i mt khu</name>
   <tag></tag>
   <elementGuidId>bb098c3b-9928-4bc5-9d8f-e7646e920c18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-group.col-lg-3.col-12.profile-email_and_password_fields_submit.pl-lg-10px > button[name=&quot;save&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='save'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cacbafc-61f2-4380-9f1b-91eb30473447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8f6bbebd-ec24-47ed-9abe-c3ed4f1d9d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>aee47ced-448c-48d4-b1d7-73909d3a3d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save btn-primary--hover profile-email_and_password_btn</value>
      <webElementGuid>7458ca96-7258-496c-a35c-4e99cd996f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>f73ff7b2-0fdd-4622-91f1-5c1c1e597e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#changePasswordModal</value>
      <webElementGuid>21687ae6-32e4-4c1c-80ee-89d8945b2e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thay đổi mật khẩu</value>
      <webElementGuid>6867e1f4-16e9-4583-abff-5d1670d852a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content&quot;]/div[@class=&quot;js-page-data page page--has_header&quot;]/div[@class=&quot;page-flex&quot;]/div[@class=&quot;container-fluid container_center_desktop profile&quot;]/div[@class=&quot;row site-main-part&quot;]/div[@class=&quot;profile_page col&quot;]/div[@class=&quot;profile-body profile-page_body&quot;]/div[@class=&quot;profile-email_and_password js-dynamic_form&quot;]/div[@class=&quot;profile-email_and_password-fields&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col-lg-3 col-12 profile-email_and_password_fields_submit pl-lg-10px&quot;]/button[@class=&quot;btn btn-save btn-primary--hover profile-email_and_password_btn&quot;]</value>
      <webElementGuid>bfdf15b6-ec3e-4c33-a886-962991e13f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='save'])[2]</value>
      <webElementGuid>821fc5ca-b1dc-41da-8c97-d46816c80d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ email'])[3]/following::button[1]</value>
      <webElementGuid>15d51a92-90be-4cfd-ae28-1cf615f691cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Địa chỉ email và mật khẩu'])[1]/following::button[1]</value>
      <webElementGuid>ada2974e-7fc7-4643-a180-62cebc0052be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM UNLINK ACCOUNT'])[1]/preceding::button[2]</value>
      <webElementGuid>7647c1b4-c673-40a1-9e17-10a37bef511b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/preceding::button[2]</value>
      <webElementGuid>78b94362-446c-4679-b911-addd7eb88a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thay đổi mật khẩu']/parent::*</value>
      <webElementGuid>08317923-0822-4ac1-872b-099f74327a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/button</value>
      <webElementGuid>2cc4606a-025f-4736-b8dd-51c62f51de32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'save' and (text() = 'Thay đổi mật khẩu' or . = 'Thay đổi mật khẩu')]</value>
      <webElementGuid>0d796964-d628-4a8b-9a3c-cb51d4261078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
