<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Xc nhn mt khu mi_dwfrm_profile_login__e0807e</name>
   <tag></tag>
   <elementGuidId>2bab83eb-19b0-4917-ba3a-3b2698ee6c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#newPasswordConfirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='newPasswordConfirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29c3301e-dbd3-410b-979d-b1b4015406d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3e9559cd-ce93-4e38-b006-53bea782f24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>75a5cb69-8034-4685-bfec-99bfe4fd94d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newPasswordConfirm</value>
      <webElementGuid>4c76161b-f719-4b69-88f3-8dee23536965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Xác nhận mật khẩu mới</value>
      <webElementGuid>5ab82417-1ba2-4aa6-a6d8-48256256c041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Nhập mật khẩu xác nhận của bạn</value>
      <webElementGuid>f0ebfdf9-9409-42b1-86ab-64a09eede585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-range-error</name>
      <type>Main</type>
      <value>Mật khẩu phải có ít nhất 8 ký tự bao gồm chữ hoa và chữ thường, và ít nhất một chữ số.</value>
      <webElementGuid>0918d59b-32fa-4b53-b2d2-9f2332d767ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>Mật khẩu phải có ít nhất 8 ký tự bao gồm chữ hoa và chữ thường, và ít nhất một chữ số.</value>
      <webElementGuid>06bc654a-198e-4061-a548-6d1c0468dd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>6883404e-868a-4138-992d-27d0c384de43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profile_login_newpasswords_newpasswordconfirm</value>
      <webElementGuid>75783967-563c-4b43-b5fb-d3681363b4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77531796-b2dc-4476-af38-4768c4dccf42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>c3af450e-013f-49bc-b5d1-da3e1708e281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>47ac2a30-7c4c-49ac-9274-b27504f03293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*\d)(?![.\n])(?=.*[A-Z])(?=.*[a-z])\S{8,}$</value>
      <webElementGuid>5e9a6338-9fc7-4e82-976f-80beb5dcdfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newPasswordConfirm&quot;)</value>
      <webElementGuid>0b2d920c-c92f-48b5-b0c2-749ac4bbb8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='newPasswordConfirm']</value>
      <webElementGuid>7e824671-4130-4ff8-92bc-cd3b2d9a43f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='changePasswordModal']/div/div/div/div[2]/div/form/div/div[3]/input</value>
      <webElementGuid>d6185439-6061-49b4-b286-a57d411aa066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[3]/input</value>
      <webElementGuid>5c841a5a-9a1f-48ec-844d-e55fa351cd90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'newPasswordConfirm' and @placeholder = 'Xác nhận mật khẩu mới' and @name = 'dwfrm_profile_login_newpasswords_newpasswordconfirm']</value>
      <webElementGuid>b8756526-62f2-432c-b49c-c39779b07456</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
