<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>ecfd0965-80f6-4ca8-88cf-c849982f4aff</testSuiteGuid>
   <testCaseLink>
      <guid>bc2fbfe2-1b72-4674-bb37-b0e7560f12b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>79d904b4-0aac-4eec-ac49-ad263b6c250a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data_test</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>79d904b4-0aac-4eec-ac49-ad263b6c250a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Usename</value>
         <variableId>450e968f-f843-4223-b894-ee8c643c9b00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d904b4-0aac-4eec-ac49-ad263b6c250a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Pass</value>
         <variableId>721e655a-8b92-42a1-8bce-aa2a4986b5ff</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
