<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ia chi email_dwfrm_profileWithMandato_066250</name>
   <tag></tag>
   <elementGuidId>7d782518-7bdd-488f-8a54-1106a914a4a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration-form-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b8d5c68-16be-40be-9252-7a8f1d5768ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>38d55c6f-4ae6-4ade-9485-040c9ae8cdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control js-email-input-with-suggestions email_input--with_suggestions is-invalid</value>
      <webElementGuid>58550619-5551-4c03-9edf-248cb0feab7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-email</value>
      <webElementGuid>c4bb3dbd-7497-4ee9-a28b-da09aa5a9042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type-mismatch</name>
      <type>Main</type>
      <value>Địa chỉ email không hợp lệ</value>
      <webElementGuid>c763192c-405b-46ef-afeb-54bc6a88ca93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-mismatch</name>
      <type>Main</type>
      <value>Địa chỉ email không hợp lệ</value>
      <webElementGuid>6002bd8e-1e85-429b-aa2a-dae196a4a263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Trường này là bắt buộc</value>
      <webElementGuid>bacf07d2-91f8-4df7-ad28-da7839a95b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>66881a75-4d4f-4ebc-8cd3-7278b6ae3149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email*</value>
      <webElementGuid>4e3de643-5f09-4b13-98a0-d55bb576794b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profileWithMandatoryFields_customer_email</value>
      <webElementGuid>b6f0dc3e-26ae-4e3a-baa1-02b922aa230e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>651a2bea-0c26-4e91-bc44-0af3ac976ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>0fdad2cc-740e-492a-b30c-c9fc2d059dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9][\w%+-]*(?:\.[\w%+-]+)*@[A-Za-z0-9][\w.-]*\.[A-Za-z]{2,6}$</value>
      <webElementGuid>6b24fb98-5b11-497b-bfbc-06fa9db12aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-email&quot;)</value>
      <webElementGuid>019840ad-1534-4b0e-a351-0475c9645c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-email']</value>
      <webElementGuid>4792fe59-2dbc-4c4f-b775-0b94e5ad6c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>fb2d8da0-7e3f-4a3f-90cc-15b6f8a69893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'registration-form-email' and @placeholder = 'Địa chỉ email*' and @name = 'dwfrm_profileWithMandatoryFields_customer_email']</value>
      <webElementGuid>d710d014-81d4-40c7-b5a4-d92e37cf5785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
