<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_H_dwfrm_profileWithMandatoryFields_cu_397aa1</name>
   <tag></tag>
   <elementGuidId>c733ef40-cfd4-4bb7-81be-0bd1d637f9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-lname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration-form-lname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed5106b0-501b-4d76-b8c3-15df0ac319da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>88ca7d23-bfed-42b7-a467-e74f5cba5903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dea6694f-ad1c-461a-9efe-794cf3efa048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-lname</value>
      <webElementGuid>cff407d8-bc5b-46b9-8d5b-72fc2c86da7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Họ*</value>
      <webElementGuid>ac56fe85-3c63-480a-a7f3-154a3b3d87ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Nhập họ của bạn</value>
      <webElementGuid>8bcd3192-5e84-4f4e-8093-197730066643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-mismatch</name>
      <type>Main</type>
      <value>Nhập định dạng họ hợp lệ</value>
      <webElementGuid>efe7f79c-8eaa-4d21-b09c-19930c548663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-range-error</name>
      <type>Main</type>
      <value>Phải có ít hơn 50 ký tự.</value>
      <webElementGuid>89267098-8d85-49c0-8da1-77a7bad03ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>83ff906a-e628-4e9a-acc6-2d12c5bd09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profileWithMandatoryFields_customer_lastname</value>
      <webElementGuid>9863423e-02f5-42ca-a592-cce3ef579ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5ac1ec9c-72f9-4228-ba64-9af153fa0b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>aa6b1056-0d28-47f8-8443-bdb62ec0e031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\u4E00-\u9FFF\u0E00-\u0E7F\uAC00-\uD7A3\u0600-\u06FF\u0041-\u005A\u0061-\u007A\u00C0-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF]*$</value>
      <webElementGuid>304de487-7a99-4cf2-9d12-1b08b15572c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-lname&quot;)</value>
      <webElementGuid>cbd05baf-14f1-409f-8f05-7fcac7a8c2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-lname']</value>
      <webElementGuid>401d6df3-ee1b-4ece-8262-354eec9af5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/form/div[2]/input</value>
      <webElementGuid>c7e2b8d2-371b-473f-bc16-8d2c821f16eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registration-form-lname' and @placeholder = 'Họ*' and @name = 'dwfrm_profileWithMandatoryFields_customer_lastname']</value>
      <webElementGuid>5d1ff9a3-ff95-44fe-adf6-fe1529780cbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
