<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_S lin lc_dwfrm_profileWithMandatoryFi_d63274</name>
   <tag></tag>
   <elementGuidId>f3868002-af3b-492c-ae8e-9c7a26f6f03f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profilePhoneNumber_dropdown_input_field']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profilePhoneNumber_dropdown_input_field</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eacdbfc1-00cb-4b50-b73c-0ef940a31db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profilePhoneNumber_dropdown_input_field</value>
      <webElementGuid>2bafd7f3-4065-477a-a74e-dbb5a7865b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2d20b08c-e5a9-4548-8f8f-3cf91490fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control dropdown_input-input_filed js-dropdown_input-input js-register-phone</value>
      <webElementGuid>e0a172b7-d281-44ad-a1aa-6bfb3e412a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Số điện thoại liên hệ</value>
      <webElementGuid>d61bb912-a959-4b17-ae9c-fd73cf1bdeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Trường này là bắt buộc</value>
      <webElementGuid>c2b43d90-cc28-452d-89b0-059da0572e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-mismatch</name>
      <type>Main</type>
      <value>Nhập số điện thoại hợp lệ</value>
      <webElementGuid>d6f51cbe-ed7f-4ce7-b1be-4a60c8d4f8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-range-error</name>
      <type>Main</type>
      <value>Nhập số điện thoại hợp lệ</value>
      <webElementGuid>fea43eea-b404-46a1-8ebb-63b9f93da57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profileWithMandatoryFields_registration_phone</value>
      <webElementGuid>1bb702ad-9c5c-4e78-b953-dec7fbca6ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efd5aa00-d966-433c-bedd-03788626706c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>e8db8258-756d-4572-a75d-6016e95d6644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>294571a7-7591-4bdf-a4cb-43a2c7cb0d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[0-9]*$</value>
      <webElementGuid>dc43a7fb-fe6f-46ea-8e4a-2150d9fb60f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>700</value>
      <webElementGuid>ff64fcbd-064b-43cf-ab54-9b3ed025d85b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-firstdigit-error</name>
      <type>Main</type>
      <value>Số điện thoại của bạn phải bắt đầu bằng chữ số 0</value>
      <webElementGuid>a9309091-683a-416f-92fc-792054618176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profilePhoneNumber_dropdown_input_field&quot;)</value>
      <webElementGuid>4cb88b02-78b8-47ad-8571-f9aa5a7fd1cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profilePhoneNumber_dropdown_input_field']</value>
      <webElementGuid>6ac95ab7-4e58-4c0c-8415-15cc0676a127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='profilePhoneNumber']/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>28178755-726c-4dc5-b1a1-332b9a951692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>a170acf8-dd2c-4178-b015-4bb06e8fa71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profilePhoneNumber_dropdown_input_field' and @type = 'tel' and @placeholder = 'Số điện thoại liên hệ' and @name = 'dwfrm_profileWithMandatoryFields_registration_phone']</value>
      <webElementGuid>b419753d-e069-4a6b-bfa1-86718191b8f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
