<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tn_dwfrm_profileWithMandatoryFields_c_d3d8a8</name>
   <tag></tag>
   <elementGuidId>5e11087e-e19d-485b-a974-e9c3e91ec88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration-form-fname']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration-form-fname</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc5ba3a7-e084-4bc3-99b0-236de9947168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5868f210-483d-48c8-8d0d-876d04b6c6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a18706c-16ec-4140-87e0-bf46bab521f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration-form-fname</value>
      <webElementGuid>c9775c93-0620-4823-b0d5-774957f3ce02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tên*</value>
      <webElementGuid>1d652076-bbb0-41bc-9c47-af3d4804cc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Nhập tên của bạn</value>
      <webElementGuid>941c7051-c097-4f89-99ac-44c0d035da83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-mismatch</name>
      <type>Main</type>
      <value>Nhập định dạng tên hợp lệ</value>
      <webElementGuid>8840a32f-c8d4-4e71-8ae7-5ba698c92c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-range-error</name>
      <type>Main</type>
      <value>Phải có ít hơn 50 ký tự.</value>
      <webElementGuid>fb0515f7-f0fc-4f2c-a6a9-356741ace00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d4f39c20-9eec-4db6-8bff-fe487d01c8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dwfrm_profileWithMandatoryFields_customer_firstname</value>
      <webElementGuid>fc728ede-6d9e-4e5c-8c79-b358c7dbc58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cacfdabc-4e91-4162-b1ac-ad2f5dcc54ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>235784fd-02b4-4bb6-9930-123959670336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[\u4E00-\u9FFF\u0E00-\u0E7F\uAC00-\uD7A3\u0600-\u06FF\u0041-\u005A\u0061-\u007A\u00C0-\u00FF\u0100-\u017F\u0180-\u024F\u1E00-\u1EFF]*$</value>
      <webElementGuid>4df1c522-cfdf-49f2-8091-b15766a1546b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration-form-fname&quot;)</value>
      <webElementGuid>56ca8880-2004-443a-9c98-b0de2ef7b637</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration-form-fname']</value>
      <webElementGuid>0e0f4fb7-80ce-4bbd-87dc-814e291210d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/form/div/input</value>
      <webElementGuid>84a76b44-29ad-4641-97f8-26226c8f3054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'registration-form-fname' and @placeholder = 'Tên*' and @name = 'dwfrm_profileWithMandatoryFields_customer_firstname']</value>
      <webElementGuid>cc2aedde-cdb6-4536-864f-bb4a9314aa20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
