<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ia chi email_loginEmail</name>
   <tag></tag>
   <elementGuidId>237a1e0e-3675-4e8e-9791-cc252c0ddece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;loginEmail&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='loginEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Địa chỉ email&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80357f47-ceb0-4120-ae2c-ee5d60b4a026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>385bac28-2e18-44d1-a166-aef2d9ecfb8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>e050530c-2e6f-4396-94a5-3a589ef68e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control js-email-input-with-suggestions email_input--with_suggestions</value>
      <webElementGuid>eb6c10c2-e6f3-4885-88b3-b0aaf081b3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginEmail</value>
      <webElementGuid>ddf3177b-be9c-415a-93a0-9628ec16efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Địa chỉ email</value>
      <webElementGuid>63818e6b-cf11-446b-af9b-46287f287c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Trường này là bắt buộc</value>
      <webElementGuid>35a942ea-fa77-4914-b070-3361f6624d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type-mismatch</name>
      <type>Main</type>
      <value>Địa chỉ email không hợp lệ</value>
      <webElementGuid>6e47014c-f440-47c1-bdfc-d7e34d730b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-mismatch</name>
      <type>Main</type>
      <value>Địa chỉ email không hợp lệ</value>
      <webElementGuid>5cc3213e-0484-4818-b13d-dc11f21b028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>014bef7f-ca97-4e87-81dc-b71b957d12ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^[A-Za-z0-9][\w%+-]*(?:\.[\w%+-]+)*@[A-Za-z0-9][\w.-]*\.[A-Za-z]{2,6}$</value>
      <webElementGuid>11d31ca2-4396-4dae-a7c6-144b33cbda0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content&quot;]/div[@class=&quot;js-page-data page page--has_header  page--home&quot;]/header[@class=&quot;page_header page_header--sticky&quot;]/div[@class=&quot;container-fluid container-fluid-md container-hd page_header-inner  js-logo_wrapper&quot;]/div[@class=&quot;page_header-item page_header-txt page_header-login&quot;]/div[@class=&quot;header_login user dropdown position-static show&quot;]/div[@class=&quot;js-header_login-menu--unregistered dropdown-menu header_login-menu header_login-menu--unregistered show&quot;]/div[@class=&quot;header_login-menu_content&quot;]/form[@class=&quot;js-login_form login_form js-chain_inline_validation_form&quot;]/div[@class=&quot;form-group c-dynamic_field custom_email_field active focused&quot;]/input[@class=&quot;form-control js-email-input-with-suggestions email_input--with_suggestions&quot;]</value>
      <webElementGuid>abfac47f-ba4d-4078-a844-940a4c8e5a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='loginEmail']</value>
      <webElementGuid>b16eccf6-f0be-465d-af6c-5bb8a1c6b76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2e8524bf-2ba4-45ae-95dc-d3203326ad47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'loginEmail' and @placeholder = 'Địa chỉ email']</value>
      <webElementGuid>ea669330-9ee2-411c-8d1b-21dff629c009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
