<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_loginPassword</name>
   <tag></tag>
   <elementGuidId>9c2cb030-40b0-4b5e-bfdc-63b2633de9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;loginPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='loginPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Mật khẩu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db6bfe2e-7e49-4773-b690-0c59fd030d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>58def67e-ca3f-4c82-9ada-5fe2fdc72891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>d3bca253-f38f-4210-bbc8-adce3ca927fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>499e41a3-cf90-42e0-b5ae-2a94804344ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>loginPassword</value>
      <webElementGuid>d902d598-51cb-4051-961e-d101e3ad23ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>fe47682a-cc67-4d30-b72e-2ad83b53fe25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-missing-error</name>
      <type>Main</type>
      <value>Trường này là bắt buộc</value>
      <webElementGuid>ade18846-0712-4b6e-8d73-7adcca3d1074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pattern-error</name>
      <type>Main</type>
      <value>Vui lòng nhập đúng với định dạng được yêu cầu.</value>
      <webElementGuid>581f7dff-3d60-4154-ad17-56eef711f010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-group</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>292167a1-b12e-4868-adc0-248e5635ba32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(?=.*\d)(?![.\n])(?=.*[A-Z])(?=.*[a-z])\S{8,}$</value>
      <webElementGuid>43c80be9-f444-4676-b2e2-fb7455a15572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;page-content&quot;]/div[@class=&quot;js-page-data page page--has_header  page--home&quot;]/header[@class=&quot;page_header page_header--sticky&quot;]/div[@class=&quot;container-fluid container-fluid-md container-hd page_header-inner  js-logo_wrapper&quot;]/div[@class=&quot;page_header-item page_header-txt page_header-login&quot;]/div[@class=&quot;header_login user dropdown position-static show&quot;]/div[@class=&quot;js-header_login-menu--unregistered dropdown-menu header_login-menu header_login-menu--unregistered show&quot;]/div[@class=&quot;header_login-menu_content&quot;]/form[@class=&quot;js-login_form login_form js-chain_inline_validation_form&quot;]/div[@class=&quot;form-group c-dynamic_field active focused&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3d3ae8e9-1868-4eb1-a762-2ff0ff8c0f9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='loginPassword']</value>
      <webElementGuid>e81feb5b-80aa-4eab-a9e3-7fc3806d366d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>d669b82b-81e5-4624-8c9f-5b2bf67d374e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'loginPassword' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>89bd6db8-48ba-4aed-a452-270377d38675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
